export const COMMON_AREA_TYPE_OPTIONS = [
  'Reception',
  'Sleeping POD',
  'Cafeteria',
  'Passage',
  'Game Room',
  'Breakout Zone',
  'Phone Booth',
  'Server Room',
  'Community Cabin',
  'Lift',
  'Staircase',
  'Emergency Exit',
  'Baby Care',
  'Store Room',
  'UPS Room',
  'AHU Room',
  'Gym',
  'Washroom',
  'Lounge',
  'Waiting Area',
  'Foyer',
  'DB/Electric Panel Room',
  'Water Station Area',
  'Printer Station',
  'CCD Area',
];
