import {
  RiInformationLine,
  RiInformationFill,
  RiTicketLine,
  RiTicketFill,
  RiBox2Line,
  RiBox2Fill,
  RiGroupLine,
  RiGroupFill,
  RiFileList2Line,
  RiFileList2Fill,
  RiBarChart2Line,
  RiBarChart2Fill,
  RiBillLine,
  RiBillFill,
  RiSettings4Line,
  RiSettings4Fill,
  RiUser2Line,
  RiUser2Fill,
  RiUserLine,
  RiUserFill,
  RiTaskLine,
  RiTaskFill,
} from 'react-icons/ri';

export const TOAST_POSITION = 'top-right';

// Month names (1–12) for selects, recurrence, filters, etc.
export const MONTH_OPTIONS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

// Columns that should always stay pinned as the first column (non-movable in column manager).
export const FIRST_COLUMN_NAME = [
  'first_name',
  'event_name',
  'orderNo',
  'product',
  'title',
  'brand_name',
  'legalName',
  'name',
  'subject',
  'task',
  'spaceName',
  'partner_name',
  'leadName',
  'stock_center',
  'subcategory',
];

export const CURRENCY = '₹';

// Mock team data for team management
export const MOCK_TEAM_DATA = [
  // Center A - All roles represented
  {
    id: 1,
    name: 'John Doe',
    center: 'Center A',
    email: 'john.doe@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 2,
    name: 'Sarah Mitchell',
    center: 'Center A',
    email: 'sarah.mitchell@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 3,
    name: 'Bob Johnson',
    center: 'Center A',
    email: 'bob.johnson@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: 1,
  },
  {
    id: 4,
    name: 'Emma Watson',
    center: 'Center A',
    email: 'emma.watson@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: -1,
  },
  {
    id: 5,
    name: 'Michael Chen',
    center: 'Center A',
    email: 'michael.chen@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 6,
    name: 'David Wilson',
    center: 'Center A',
    email: 'david.wilson@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 7,
    name: 'Lisa Anderson',
    center: 'Center A',
    email: 'lisa.anderson@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 8,
    name: 'James Brown',
    center: 'Center A',
    email: 'james.brown@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 9,
    name: 'Robert Taylor',
    center: 'Center A',
    email: 'robert.taylor@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  // Center B - All roles represented
  {
    id: 10,
    name: 'Alkesh Sharma',
    center: 'Center B',
    email: 'alkesh_sharma@pantry.com',
    role: 'PANTRY BOY',
    status: 'Inactive',
    team: 'others',
    present: -1,
  },
  {
    id: 11,
    name: 'Priya Patel',
    center: 'Center B',
    email: 'priya.patel@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 12,
    name: 'Rajesh Kumar',
    center: 'Center B',
    email: 'rajesh.kumar@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: 0,
  },
  {
    id: 13,
    name: 'Anita Singh',
    center: 'Center B',
    email: 'anita.singh@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 14,
    name: 'Charlie Davis',
    center: 'Center B',
    email: 'charlie.davis@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 15,
    name: 'Sophie Martin',
    center: 'Center B',
    email: 'sophie.martin@example.com',
    role: 'SUPERVISOR',
    status: 'Inactive',
    team: 'others',
    present: 0,
  },
  {
    id: 16,
    name: 'Kevin Lee',
    center: 'Center B',
    email: 'kevin.lee@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 17,
    name: 'Maria Garcia',
    center: 'Center B',
    email: 'maria.garcia@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 18,
    name: 'Tom Anderson',
    center: 'Center B',
    email: 'tom.anderson@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: -1,
  },
  // Center C - All roles represented
  {
    id: 19,
    name: 'Alice Brown',
    center: 'Center C',
    email: 'alice.brown@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 0,
  },
  {
    id: 20,
    name: 'Peter White',
    center: 'Center C',
    email: 'peter.white@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 21,
    name: 'Jennifer Lopez',
    center: 'Center C',
    email: 'jennifer.lopez@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: -1,
  },
  {
    id: 22,
    name: 'Daniel Kim',
    center: 'Center C',
    email: 'daniel.kim@example.com',
    role: 'SECURITY STAFF',
    status: 'Inactive',
    team: 'security',
    present: 0,
  },
  {
    id: 23,
    name: 'Rachel Green',
    center: 'Center C',
    email: 'rachel.green@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 24,
    name: 'Chris Evans',
    center: 'Center C',
    email: 'chris.evans@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 25,
    name: 'Amanda Smith',
    center: 'Center C',
    email: 'amanda.smith@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 26,
    name: 'Ryan Murphy',
    center: 'Center C',
    email: 'ryan.murphy@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 27,
    name: 'Nicole Williams',
    center: 'Center C',
    email: 'nicole.williams@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  // Center D - All roles represented
  {
    id: 28,
    name: 'Mark Thompson',
    center: 'Center D',
    email: 'mark.thompson@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 29,
    name: 'Laura Davis',
    center: 'Center D',
    email: 'laura.davis@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 30,
    name: 'Steven Miller',
    center: 'Center D',
    email: 'steven.miller@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: -1,
  },
  {
    id: 31,
    name: 'Karen White',
    center: 'Center D',
    email: 'karen.white@example.com',
    role: 'HK STAFF',
    status: 'Inactive',
    team: 'hk',
    present: 0,
  },
  {
    id: 32,
    name: 'Brian Johnson',
    center: 'Center D',
    email: 'brian.johnson@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 33,
    name: 'Michelle Adams',
    center: 'Center D',
    email: 'michelle.adams@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 34,
    name: 'Jason Wilson',
    center: 'Center D',
    email: 'jason.wilson@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 35,
    name: 'Patricia Moore',
    center: 'Center D',
    email: 'patricia.moore@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 36,
    name: 'Andrew Taylor',
    center: 'Center D',
    email: 'andrew.taylor@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  // Center E - All roles represented
  {
    id: 37,
    name: 'Jessica Martinez',
    center: 'Center E',
    email: 'jessica.martinez@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: -1,
  },
  {
    id: 38,
    name: 'Christopher Lee',
    center: 'Center E',
    email: 'christopher.lee@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 39,
    name: 'Melissa Harris',
    center: 'Center E',
    email: 'melissa.harris@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: 0,
  },
  {
    id: 40,
    name: 'Nathan Clark',
    center: 'Center E',
    email: 'nathan.clark@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 41,
    name: 'Stephanie Lewis',
    center: 'Center E',
    email: 'stephanie.lewis@example.com',
    role: 'MST',
    status: 'Inactive',
    team: 'fm',
    present: -1,
  },
  {
    id: 42,
    name: 'Brandon Walker',
    center: 'Center E',
    email: 'brandon.walker@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 43,
    name: 'Cynthia Young',
    center: 'Center E',
    email: 'cynthia.young@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 44,
    name: 'Eric King',
    center: 'Center E',
    email: 'eric.king@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 45,
    name: 'Angela Wright',
    center: 'Center E',
    email: 'angela.wright@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: -1,
  },
  // Center F - All roles represented
  {
    id: 46,
    name: 'Justin Scott',
    center: 'Center F',
    email: 'justin.scott@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 47,
    name: 'Brittany Green',
    center: 'Center F',
    email: 'brittany.green@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 48,
    name: 'Tyler Adams',
    center: 'Center F',
    email: 'tyler.adams@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: -1,
  },
  {
    id: 49,
    name: 'Samantha Baker',
    center: 'Center F',
    email: 'samantha.baker@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 50,
    name: 'Jordan Hill',
    center: 'Center F',
    email: 'jordan.hill@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 51,
    name: 'Megan Campbell',
    center: 'Center F',
    email: 'megan.campbell@example.com',
    role: 'SUPERVISOR',
    status: 'Inactive',
    team: 'others',
    present: -1,
  },
  {
    id: 52,
    name: 'Derek Mitchell',
    center: 'Center F',
    email: 'derek.mitchell@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 53,
    name: 'Olivia Carter',
    center: 'Center F',
    email: 'olivia.carter@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 54,
    name: 'Logan Phillips',
    center: 'Center F',
    email: 'logan.phillips@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  // Center G - All roles represented
  {
    id: 55,
    name: 'Victoria Turner',
    center: 'Center G',
    email: 'victoria.turner@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 56,
    name: 'Alexander Reed',
    center: 'Center G',
    email: 'alexander.reed@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 57,
    name: 'Isabella Cooper',
    center: 'Center G',
    email: 'isabella.cooper@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: 1,
  },
  {
    id: 58,
    name: 'Benjamin Foster',
    center: 'Center G',
    email: 'benjamin.foster@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: -1,
  },
  {
    id: 59,
    name: 'Grace Morgan',
    center: 'Center G',
    email: 'grace.morgan@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 60,
    name: 'Daniel Ross',
    center: 'Center G',
    email: 'daniel.ross@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 61,
    name: 'Hannah Bell',
    center: 'Center G',
    email: 'hannah.bell@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 62,
    name: 'Samuel Price',
    center: 'Center G',
    email: 'samuel.price@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 63,
    name: 'Lily Bennett',
    center: 'Center G',
    email: 'lily.bennett@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  {
    id: 64,
    name: 'Ethan Wood',
    center: 'Center G',
    email: 'ethan.wood@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 0,
  },
  // Center H - All roles represented
  {
    id: 65,
    name: 'Chloe Barnes',
    center: 'Center H',
    email: 'chloe.barnes@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: -1,
  },
  {
    id: 66,
    name: 'Noah Richardson',
    center: 'Center H',
    email: 'noah.richardson@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 67,
    name: 'Ava Cox',
    center: 'Center H',
    email: 'ava.cox@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: 0,
  },
  {
    id: 68,
    name: 'Mason Howard',
    center: 'Center H',
    email: 'mason.howard@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 69,
    name: 'Zoe Ward',
    center: 'Center H',
    email: 'zoe.ward@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 70,
    name: 'Lucas Torres',
    center: 'Center H',
    email: 'lucas.torres@example.com',
    role: 'SUPERVISOR',
    status: 'Inactive',
    team: 'others',
    present: 0,
  },
  {
    id: 71,
    name: 'Mia Peterson',
    center: 'Center H',
    email: 'mia.peterson@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 72,
    name: 'Aiden Gray',
    center: 'Center H',
    email: 'aiden.gray@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 73,
    name: 'Emma Ramirez',
    center: 'Center H',
    email: 'emma.ramirez@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: -1,
  },
  {
    id: 74,
    name: 'Jameson Brooks',
    center: 'Center H',
    email: 'jameson.brooks@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 0,
  },
  {
    id: 75,
    name: 'Sophia Kelly',
    center: 'Center H',
    email: 'sophia.kelly@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  // Center I - All roles represented
  {
    id: 76,
    name: 'Jackson Sanders',
    center: 'Center I',
    email: 'jackson.sanders@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 77,
    name: 'Charlotte Price',
    center: 'Center I',
    email: 'charlotte.price@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 78,
    name: 'Liam Bennett',
    center: 'Center I',
    email: 'liam.bennett@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: -1,
  },
  {
    id: 79,
    name: 'Amelia Wood',
    center: 'Center I',
    email: 'amelia.wood@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 80,
    name: 'Harper Barnes',
    center: 'Center I',
    email: 'harper.barnes@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 81,
    name: 'Evelyn Richardson',
    center: 'Center I',
    email: 'evelyn.richardson@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 82,
    name: 'Oliver Cox',
    center: 'Center I',
    email: 'oliver.cox@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 83,
    name: 'Abigail Howard',
    center: 'Center I',
    email: 'abigail.howard@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 84,
    name: 'William Ward',
    center: 'Center I',
    email: 'william.ward@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 0,
  },
  {
    id: 85,
    name: 'Emily Torres',
    center: 'Center I',
    email: 'emily.torres@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  {
    id: 86,
    name: 'Henry Peterson',
    center: 'Center I',
    email: 'henry.peterson@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: -1,
  },
  // Center J - All roles represented
  {
    id: 87,
    name: 'Madison Gray',
    center: 'Center J',
    email: 'madison.gray@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 88,
    name: 'Sebastian Ramirez',
    center: 'Center J',
    email: 'sebastian.ramirez@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 89,
    name: 'Scarlett Brooks',
    center: 'Center J',
    email: 'scarlett.brooks@example.com',
    role: 'SECURITY STAFF',
    status: 'Inactive',
    team: 'security',
    present: -1,
  },
  {
    id: 90,
    name: 'Aria Kelly',
    center: 'Center J',
    email: 'aria.kelly@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 91,
    name: 'Carter Sanders',
    center: 'Center J',
    email: 'carter.sanders@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 92,
    name: 'Luna Price',
    center: 'Center J',
    email: 'luna.price@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 93,
    name: 'Wyatt Bennett',
    center: 'Center J',
    email: 'wyatt.bennett@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 94,
    name: 'Layla Wood',
    center: 'Center J',
    email: 'layla.wood@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 95,
    name: 'Owen Barnes',
    center: 'Center J',
    email: 'owen.barnes@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 0,
  },
  {
    id: 96,
    name: 'Penelope Richardson',
    center: 'Center J',
    email: 'penelope.richardson@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  {
    id: 97,
    name: 'Grayson Cox',
    center: 'Center J',
    email: 'grayson.cox@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: -1,
  },
  // Center K - All roles represented
  {
    id: 98,
    name: 'Riley Howard',
    center: 'Center K',
    email: 'riley.howard@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 99,
    name: 'Nora Ward',
    center: 'Center K',
    email: 'nora.ward@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: 0,
  },
  {
    id: 100,
    name: 'Levi Torres',
    center: 'Center K',
    email: 'levi.torres@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: -1,
  },
  {
    id: 101,
    name: 'Hazel Peterson',
    center: 'Center K',
    email: 'hazel.peterson@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 102,
    name: 'Elijah Gray',
    center: 'Center K',
    email: 'elijah.gray@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 103,
    name: 'Violet Ramirez',
    center: 'Center K',
    email: 'violet.ramirez@example.com',
    role: 'SUPERVISOR',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 104,
    name: 'Caleb Brooks',
    center: 'Center K',
    email: 'caleb.brooks@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 105,
    name: 'Aurora Kelly',
    center: 'Center K',
    email: 'aurora.kelly@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 106,
    name: 'Isaac Sanders',
    center: 'Center K',
    email: 'isaac.sanders@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 0,
  },
  {
    id: 107,
    name: 'Savannah Price',
    center: 'Center K',
    email: 'savannah.price@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 1,
  },
  {
    id: 108,
    name: 'Luke Bennett',
    center: 'Center K',
    email: 'luke.bennett@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: -1,
  },
  {
    id: 109,
    name: 'Audrey Wood',
    center: 'Center K',
    email: 'audrey.wood@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 0,
  },
  // Center L - All roles represented
  {
    id: 110,
    name: 'Julian Barnes',
    center: 'Center L',
    email: 'julian.barnes@example.com',
    role: 'OFFICE BOY',
    status: 'Active',
    team: 'others',
    present: 1,
  },
  {
    id: 111,
    name: 'Claire Richardson',
    center: 'Center L',
    email: 'claire.richardson@example.com',
    role: 'PANTRY BOY',
    status: 'Active',
    team: 'others',
    present: -1,
  },
  {
    id: 112,
    name: 'Aaron Cox',
    center: 'Center L',
    email: 'aaron.cox@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: 0,
  },
  {
    id: 113,
    name: 'Skylar Howard',
    center: 'Center L',
    email: 'skylar.howard@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 114,
    name: 'Paisley Ward',
    center: 'Center L',
    email: 'paisley.ward@example.com',
    role: 'MST',
    status: 'Active',
    team: 'fm',
    present: -1,
  },
  {
    id: 115,
    name: 'Eli Torres',
    center: 'Center L',
    email: 'eli.torres@example.com',
    role: 'SUPERVISOR',
    status: 'Inactive',
    team: 'others',
    present: 1,
  },
  {
    id: 116,
    name: 'Willow Peterson',
    center: 'Center L',
    email: 'willow.peterson@example.com',
    role: 'FACILITY MANAGER',
    status: 'Active',
    team: 'fm',
    present: 0,
  },
  {
    id: 117,
    name: 'Nathan Gray',
    center: 'Center L',
    email: 'nathan.gray@example.com',
    role: 'FACILITY LEAD',
    status: 'Active',
    team: 'fm',
    present: 1,
  },
  {
    id: 118,
    name: 'Bella Ramirez',
    center: 'Center L',
    email: 'bella.ramirez@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: -1,
  },
  {
    id: 119,
    name: 'Stella Brooks',
    center: 'Center L',
    email: 'stella.brooks@example.com',
    role: 'CRM',
    status: 'Active',
    team: 'crm',
    present: 0,
  },
  {
    id: 120,
    name: 'Natalie Kelly',
    center: 'Center L',
    email: 'natalie.kelly@example.com',
    role: 'HK STAFF',
    status: 'Active',
    team: 'hk',
    present: 1,
  },
  {
    id: 121,
    name: 'Maya Sanders',
    center: 'Center L',
    email: 'maya.sanders@example.com',
    role: 'SECURITY STAFF',
    status: 'Active',
    team: 'security',
    present: -1,
  },
];

export const CENTER_DETAIL_TAB_READ_MODULE = Object.freeze({
  'about-center': 'Center',
  preboarding: 'Center',
  tickets: 'HD Ticket',
  space: 'Space',
  clients: 'Customer',
  teams: 'Center',
  opex: 'Operating Expenses',
  billing: 'Client Billing',
  'p&l': null,
  configuration: 'Center Tracker Task',
  landlords: 'Landlord',
});

export const CENTER_MAIN_TAB_DEFS = [
  {
    value: 'about-center',
    label: 'About Center',
    iconLine: RiInformationLine,
    iconFill: RiInformationFill,
  },
  {
    value: 'preboarding',
    label: 'Preboarding Tasks',
    iconLine: RiTaskLine,
    iconFill: RiTaskFill,
  },
  { value: 'tickets', label: 'Tickets', iconLine: RiTicketLine, iconFill: RiTicketFill },
  { value: 'space', label: 'Space', iconLine: RiBox2Line, iconFill: RiBox2Fill },
  { value: 'clients', label: 'Clients', iconLine: RiUserLine, iconFill: RiUserFill },
  { value: 'teams', label: 'Teams', iconLine: RiGroupLine, iconFill: RiGroupFill },
  {
    value: 'opex',
    label: 'OPEX',
    iconLine: RiFileList2Line,
    iconFill: RiFileList2Fill,
  },
  {
    value: 'billing',
    label: 'Billing',
    iconLine: RiBillLine,
    iconFill: RiBillFill,
  },
  {
    value: 'p&l',
    label: 'P&L',
    iconLine: RiBarChart2Line,
    iconFill: RiBarChart2Fill,
  },
  {
    value: 'configuration',
    label: 'Configuration',
    iconLine: RiSettings4Line,
    iconFill: RiSettings4Fill,
  },
  {
    value: 'landlords',
    label: 'Landlords',
    iconLine: RiUser2Line,
    iconFill: RiUser2Fill,
  },
];
