import React from 'react';
import {
  RiAccountCircleLine,
  RiAlertLine,
  RiArticleLine,
  RiBarChartBoxLine,
  RiBarChartGroupedLine,
  RiBarChartHorizontalLine,
  RiBookOpenLine,
  RiBox3Line,
  RiBuilding4Line,
  RiBuildingLine,
  RiCalendarCheckLine,
  RiCalendarLine,
  RiCashLine,
  RiCheckboxLine,
  RiCoinLine,
  RiCupLine,
  RiDashboardLine,
  RiDonutChartLine,
  RiFileList2Line,
  RiFilePptLine,
  RiFileTextLine,
  RiFlashlightLine,
  RiFlowChart,
  RiFocus2Line,
  RiFolder2Line,
  RiFolderChartLine,
  RiFoggyLine,
  RiFloodLine,
  RiGitBranchLine,
  RiGroupLine,
  RiHammerLine,
  RiHome4Line,
  RiHomeSmile2Line,
  RiHourglassLine,
  RiInboxLine,
  RiLayoutGridLine,
  RiLineChartLine,
  RiListCheck3,
  RiMessage2Line,
  RiMessage3Line,
  RiMicLine,
  RiMoneyDollarCircleLine,
  RiMovieLine,
  RiNurseLine,
  RiOrganizationChart,
  RiPaintBrushLine,
  RiPercentLine,
  RiPieChartLine,
  RiPriceTag3Line,
  RiRadioLine,
  RiSettings2Line,
  RiSettings3Line,
  RiShakeHandsLine,
  RiShoppingCartLine,
  RiSparkling2Line,
  RiTaskLine,
  RiTeamLine,
  RiTicketLine,
  RiTimeLine,
  RiUser2Line,
  RiUserFollowLine,
  RiUserLine,
  RiUserReceivedLine,
  RiUserSettingsLine,
  RiUserSharedLine,
  RiUserStarLine,
  RiWallet3Line,
} from 'react-icons/ri';

/**
 * Dashboard icon picker — only icons already used in the app design system
 * (sidebar, charts, CRM, tickets, etc.) and verified in react-icons/ri.
 */
export const DASHBOARD_ICONS = [
  { id: 'RiFlashlightLine', label: 'Flashlight', Icon: RiFlashlightLine },
  { id: 'RiMoneyDollarCircleLine', label: 'Money', Icon: RiMoneyDollarCircleLine },
  { id: 'RiBuildingLine', label: 'Building', Icon: RiBuildingLine },
  { id: 'RiTicketLine', label: 'Ticket', Icon: RiTicketLine },
  { id: 'RiLayoutGridLine', label: 'Grid', Icon: RiLayoutGridLine },
  { id: 'RiLineChartLine', label: 'Line Chart', Icon: RiLineChartLine },
  { id: 'RiPieChartLine', label: 'Pie Chart', Icon: RiPieChartLine },
  { id: 'RiUserLine', label: 'User', Icon: RiUserLine },
  { id: 'RiNurseLine', label: 'Nurse', Icon: RiNurseLine },
  { id: 'RiTaskLine', label: 'Task', Icon: RiTaskLine },
  { id: 'RiFloodLine', label: 'Flood', Icon: RiFloodLine },
  { id: 'RiFlowChart', label: 'Flow Chart', Icon: RiFlowChart },
  { id: 'RiPriceTag3Line', label: 'Price Tag', Icon: RiPriceTag3Line },
  { id: 'RiBookOpenLine', label: 'Book', Icon: RiBookOpenLine },
  { id: 'RiRadioLine', label: 'Radio', Icon: RiRadioLine },
  { id: 'RiCalendarCheckLine', label: 'Calendar', Icon: RiCalendarCheckLine },
  { id: 'RiCheckboxLine', label: 'Checkbox', Icon: RiCheckboxLine },
  { id: 'RiListCheck3', label: 'List Check', Icon: RiListCheck3 },
  { id: 'RiFilePptLine', label: 'Presentation', Icon: RiFilePptLine },
  { id: 'RiFolder2Line', label: 'Folder', Icon: RiFolder2Line },
  { id: 'RiFolderChartLine', label: 'Folder Chart', Icon: RiFolderChartLine },
  { id: 'RiCashLine', label: 'Cash', Icon: RiCashLine },
  { id: 'RiFoggyLine', label: 'Foggy', Icon: RiFoggyLine },
  { id: 'RiMessage2Line', label: 'Message', Icon: RiMessage2Line },
  { id: 'RiBuilding4Line', label: 'Office', Icon: RiBuilding4Line },
  { id: 'RiHomeSmile2Line', label: 'Home', Icon: RiHomeSmile2Line },
  { id: 'RiShoppingCartLine', label: 'Cart', Icon: RiShoppingCartLine },
  { id: 'RiPercentLine', label: 'Percent', Icon: RiPercentLine },
  { id: 'RiHome4Line', label: 'House', Icon: RiHome4Line },
  { id: 'RiUserFollowLine', label: 'User Follow', Icon: RiUserFollowLine },
  { id: 'RiUserStarLine', label: 'User Star', Icon: RiUserStarLine },
  { id: 'RiMovieLine', label: 'Movie', Icon: RiMovieLine },
  { id: 'RiPaintBrushLine', label: 'Paint', Icon: RiPaintBrushLine },
  { id: 'RiSparkling2Line', label: 'Sparkle', Icon: RiSparkling2Line },
  { id: 'RiCupLine', label: 'Cup', Icon: RiCupLine },
  { id: 'RiWallet3Line', label: 'Wallet', Icon: RiWallet3Line },
  { id: 'RiFocus2Line', label: 'Focus', Icon: RiFocus2Line },
  { id: 'RiUserSettingsLine', label: 'User Settings', Icon: RiUserSettingsLine },
  { id: 'RiOrganizationChart', label: 'Org Chart', Icon: RiOrganizationChart },
  { id: 'RiSettings3Line', label: 'Settings', Icon: RiSettings3Line },
  { id: 'RiTimeLine', label: 'Time', Icon: RiTimeLine },
  { id: 'RiHourglassLine', label: 'Hourglass', Icon: RiHourglassLine },
  { id: 'RiMessage3Line', label: 'Chat', Icon: RiMessage3Line },
  { id: 'RiDashboardLine', label: 'Dashboard', Icon: RiDashboardLine },
  { id: 'RiBarChartBoxLine', label: 'Bar Chart', Icon: RiBarChartBoxLine },
  { id: 'RiBarChartGroupedLine', label: 'Grouped Bar', Icon: RiBarChartGroupedLine },
  { id: 'RiBarChartHorizontalLine', label: 'Horizontal Bar', Icon: RiBarChartHorizontalLine },
  { id: 'RiDonutChartLine', label: 'Donut Chart', Icon: RiDonutChartLine },
  { id: 'RiCoinLine', label: 'KPI', Icon: RiCoinLine },
  { id: 'RiCalendarLine', label: 'Calendar', Icon: RiCalendarLine },
  { id: 'RiTeamLine', label: 'Team', Icon: RiTeamLine },
  { id: 'RiGroupLine', label: 'Group', Icon: RiGroupLine },
  { id: 'RiFileList2Line', label: 'File List', Icon: RiFileList2Line },
  { id: 'RiFileTextLine', label: 'Document', Icon: RiFileTextLine },
  { id: 'RiInboxLine', label: 'Inbox', Icon: RiInboxLine },
  { id: 'RiBox3Line', label: 'Box', Icon: RiBox3Line },
  { id: 'RiUser2Line', label: 'User Alt', Icon: RiUser2Line },
  { id: 'RiAccountCircleLine', label: 'Account', Icon: RiAccountCircleLine },
  { id: 'RiShakeHandsLine', label: 'Partnership', Icon: RiShakeHandsLine },
  { id: 'RiUserReceivedLine', label: 'User Received', Icon: RiUserReceivedLine },
  { id: 'RiUserSharedLine', label: 'User Shared', Icon: RiUserSharedLine },
  { id: 'RiHammerLine', label: 'Tools', Icon: RiHammerLine },
  { id: 'RiAlertLine', label: 'Alert', Icon: RiAlertLine },
  { id: 'RiArticleLine', label: 'Article', Icon: RiArticleLine },
  { id: 'RiGitBranchLine', label: 'Branch', Icon: RiGitBranchLine },
  { id: 'RiSettings2Line', label: 'Settings Alt', Icon: RiSettings2Line },
  { id: 'RiMicLine', label: 'Microphone', Icon: RiMicLine },
];

const ICON_MAP = Object.fromEntries(DASHBOARD_ICONS.map((item) => [item.id, item.Icon]));

export function resolveDashboardIcon(iconId) {
  if (!iconId) return null;
  const trimmed = String(iconId).trim();
  if (!trimmed) return null;
  return ICON_MAP[trimmed] ?? null;
}

export function DashboardIcon({ iconId, className, size = 20 }) {
  const IconComponent = resolveDashboardIcon(iconId);
  if (IconComponent) {
    return <IconComponent className={className} size={size} />;
  }
  if (iconId) {
    return <span className={className}>{iconId}</span>;
  }
  return null;
}
