export const EMPLOYEES_DATA = [
  {
    name: 'Aarav Mehta',
    email: 'aarav.mehta@example.com',
    phone: '9876543210',
    department: 'Engineering',
    designation: 'Frontend Developer',
    DOB: '1998-04-12',
    center: 'Ahmedabad',
    seat: 'A-101',
    access: 'User',
    status: 'Active',
  },
  {
    name: 'Diya Shah',
    email: 'diya.shah@example.com',
    phone: '9123456780',
    department: 'HR',
    designation: 'HR Manager',
    DOB: '1995-09-23',
    center: 'Mumbai',
    seat: 'B-202',
    access: 'Admin',
    status: 'Active',
  },
  {
    name: 'Rohan Patel',
    email: 'rohan.patel@example.com',
    phone: '9988776655',
    department: 'Finance',
    designation: 'Accountant',
    DOB: '1993-02-15',
    center: 'Pune',
    seat: 'C-303',
    access: 'User',
    status: 'Inactive',
  },
  {
    name: 'Ishita Verma',
    email: 'ishita.verma@example.com',
    phone: '9090909090',
    department: 'Marketing',
    designation: 'SEO Specialist',
    DOB: '1997-07-08',
    center: 'Delhi',
    seat: 'D-404',
    access: 'User',
    status: 'Active',
  },
  {
    name: 'Karan Singh',
    email: 'karan.singh@example.com',
    phone: '9812345678',
    department: 'Engineering',
    designation: 'Backend Developer',
    DOB: '1996-11-30',
    center: 'Bangalore',
    seat: 'E-505',
    access: 'Admin',
    status: 'Active',
  },
  {
    name: 'Neha Joshi',
    email: 'neha.joshi@example.com',
    phone: '9345678123',
    department: 'Support',
    designation: 'Support Executive',
    DOB: '1999-03-18',
    center: 'Ahmedabad',
    seat: 'F-606',
    access: 'User',
    status: 'Inactive',
  },
  {
    name: 'Aditya Kapoor',
    email: 'aditya.kapoor@example.com',
    phone: '9765432109',
    department: 'Engineering',
    designation: 'Full Stack Developer',
    DOB: '1994-05-25',
    center: 'Gurgaon',
    seat: 'G-707',
    access: 'Admin',
    status: 'Active',
  },
  {
    name: 'Priya Nair',
    email: 'priya.nair@example.com',
    phone: '9012345678',
    department: 'Design',
    designation: 'UI/UX Designer',
    DOB: '1998-08-14',
    center: 'Kochi',
    seat: 'H-808',
    access: 'User',
    status: 'Active',
  },
  {
    name: 'Rahul Das',
    email: 'rahul.das@example.com',
    phone: '9898989898',
    department: 'Operations',
    designation: 'Operations Manager',
    DOB: '1992-01-10',
    center: 'Kolkata',
    seat: 'I-909',
    access: 'Admin',
    status: 'Inactive',
  },
  {
    name: 'Sneha Kulkarni',
    email: 'sneha.k@example.com',
    phone: '9234567890',
    department: 'Finance',
    designation: 'Financial Analyst',
    DOB: '1997-12-05',
    center: 'Pune',
    seat: 'J-110',
    access: 'User',
    status: 'Active',
  },
  {
    name: 'Manish Yadav',
    email: 'manish.yadav@example.com',
    phone: '9876501234',
    department: 'Engineering',
    designation: 'DevOps Engineer',
    DOB: '1993-06-21',
    center: 'Noida',
    seat: 'K-120',
    access: 'Admin',
    status: 'Active',
  },
  {
    name: 'Ananya Iyer',
    email: 'ananya.iyer@example.com',
    phone: '9123098765',
    department: 'Marketing',
    designation: 'Content Strategist',
    DOB: '1996-10-11',
    center: 'Chennai',
    seat: 'L-130',
    access: 'User',
    status: 'Inactive',
  },
  {
    name: 'Vikram Rathore',
    email: 'vikram.r@example.com',
    phone: '9001122334',
    department: 'Security',
    designation: 'Security Analyst',
    DOB: '1991-04-04',
    center: 'Jaipur',
    seat: 'M-140',
    access: 'Admin',
    status: 'Active',
  },
  {
    name: 'Pooja Bansal',
    email: 'pooja.b@example.com',
    phone: '9811223344',
    department: 'HR',
    designation: 'Recruiter',
    DOB: '1998-02-27',
    center: 'Delhi',
    seat: 'N-150',
    access: 'User',
    status: 'Active',
  },
  {
    name: 'Siddharth Jain',
    email: 'sid.jain@example.com',
    phone: '9091122334',
    department: 'Legal',
    designation: 'Legal Advisor',
    DOB: '1990-09-09',
    center: 'Mumbai',
    seat: 'O-160',
    access: 'Admin',
    status: 'Inactive',
  },
  {
    name: 'Ritika Sen',
    email: 'ritika.sen@example.com',
    phone: '9898123456',
    department: 'Design',
    designation: 'Graphic Designer',
    DOB: '1999-07-19',
    center: 'Kolkata',
    seat: 'P-170',
    access: 'User',
    status: 'Active',
  },
  {
    name: 'Harsh Vardhan',
    email: 'harsh.v@example.com',
    phone: '9765001122',
    department: 'Engineering',
    designation: 'QA Engineer',
    DOB: '1995-03-03',
    center: 'Hyderabad',
    seat: 'Q-180',
    access: 'User',
    status: 'Inactive',
  },
  {
    name: 'Meera Kapoor',
    email: 'meera.k@example.com',
    phone: '9011987654',
    department: 'Sales',
    designation: 'Sales Executive',
    DOB: '1997-11-22',
    center: 'Chandigarh',
    seat: 'R-190',
    access: 'User',
    status: 'Active',
  },
  {
    name: 'Arjun Reddy',
    email: 'arjun.reddy@example.com',
    phone: '9123451234',
    department: 'Operations',
    designation: 'Operations Executive',
    DOB: '1994-06-16',
    center: 'Hyderabad',
    seat: 'S-200',
    access: 'Admin',
    status: 'Active',
  },
  {
    name: 'Tanvi Desai',
    email: 'tanvi.desai@example.com',
    phone: '9988112233',
    department: 'Support',
    designation: 'Customer Support',
    DOB: '2000-01-01',
    center: 'Ahmedabad',
    seat: 'T-210',
    access: 'User',
    status: 'Active',
  },
];

const uniqSorted = (values) => [...new Set(values)].sort((a, b) => a.localeCompare(b));

/** Radix Select options: department quick filter (includes All). */
export const DEPARTMENT_FILTER_OPTIONS = [
  { value: 'all', label: 'All Departments' },
  ...uniqSorted(EMPLOYEES_DATA.map((r) => r.department)).map((d) => ({
    value: d,
    label: d,
  })),
];

/** Status values match `EMPLOYEES_DATA[].status`. */
export const STATUS_FILTER_OPTIONS = [
  { value: 'all', label: 'All Status' },
  { value: 'Active', label: 'Active' },
  { value: 'Inactive', label: 'Inactive' },
];

/** Access values match `EMPLOYEES_DATA[].access`. */
export const ACCESS_FILTER_OPTIONS = [
  { value: 'all', label: 'All Access' },
  { value: 'User', label: 'User' },
  { value: 'Admin', label: 'Admin' },
];
